name: Manual CDK Deployment

on:
  workflow_dispatch:

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS CLI profile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_PROFILE: myprofile
        run: |
          npm install -g aws-cli
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
          aws configure set profile.$AWS_PROFILE.region $AWS_DEFAULT_REGION

      - name: Deploy CDK stack
        run: npx aws-cdk deploy --profile $AWS_PROFILE faces-cdk-project --require-approval never
          
