name: Manual CDK Deployment

on:
  workflow_dispatch:

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS CLI profile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_PROFILE: myprofile
        run: |
          npm install -g aws-cli
          aws configure --profile $AWS_PROFILE set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure --profile $AWS_PROFILE set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure --profile $AWS_PROFILE set region $AWS_DEFAULT_REGION

      - name: Deploy CDK stack
        env:
          CLARIFAI_API_KEY: ${{ secrets.CLARIFAI_API_KEY }}
          CLARIFAI_PAT_KEY: ${{ secrets.CLARIFAI_PAT_KEY }}
          CLARIFAI_USER_ID: ${{ secrets.CLARIFAI_USER_ID }}
          CLARIFAI_APP_ID: ${{ secrets.CLARIFAI_APP_ID }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
        run: npx aws-cdk deploy --profile $AWS_PROFILE FacesCdkProjectStack -a ./faces-cdk-project --require-approval never
          
